stages:
    - test
    - build

variables:
    CONTAINER_API_URL: "${CI_REGISTRY_IMAGE}/ssm-bats-rest-api"
    FUSEKI_VERSION: "3.17.0"

include:
    remote: "https://code.ornl.gov/rse-deployment/rse-sharables/-/raw/master/.gitlab-ci-before_script.yml"

lint:
    stage: test
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f src/main/docker/Dockerfile.ssm_bats_rest_api -t ssm-bats-test .
        - docker run --net=host -v /var/run/docker.sock:/var/run/docker.sock ssm-bats-test /bin/bash -c "mvn validate"
        - func_rse_docker_cleanup
    tags:
        - rse-ssm-builder

test:
    stage: test
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull ${CI_REGISTRY_IMAGE}/openjdk:11-jre-slim
        - docker pull ${CI_REGISTRY_IMAGE}/fuseki:${FUSEKI_VERSION}
        - docker build -f src/main/docker/Dockerfile.ssm_bats_rest_api -t ssm-bats-test .
        - docker run --net=host -v /var/run/docker.sock:/var/run/docker.sock ssm-bats-test
        - func_rse_docker_cleanup
    tags:
        - rse-ssm-builder

coverage:
    stage: test
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull ${CI_REGISTRY_IMAGE}/openjdk:11-jre-slim
        - docker pull ${CI_REGISTRY_IMAGE}/fuseki:${FUSEKI_VERSION}
        - docker build -f src/main/docker/Dockerfile.ssm_bats_rest_api -t ssm-bats-test .
        - docker run --net=host -v /var/run/docker.sock:/var/run/docker.sock ssm-bats-test /bin/bash -c "mvn clean docker:build verify; awk  -F',' '{ instructions += \$4 + \$5; covered += \$5 } END { print covered, \"/\", instructions, \" instructions covered\"; print 100*covered/instructions, \"% covered\" }' target/site/jacoco/jacoco.csv"
        - func_rse_docker_cleanup
    tags:
        - rse-ssm-builder

.build:
    stage: build
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f Dockerfile --build-arg PROFILE=${PROFILE} -t $CONTAINER_API_URL/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA .
        - docker tag $CONTAINER_API_URL/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA $CONTAINER_API_URL/$CI_COMMIT_REF_NAME:latest
        - docker push $CONTAINER_API_URL/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
        - docker push $CONTAINER_API_URL/$CI_COMMIT_REF_NAME:latest
    tags:
        - rse-ssm-builder

build-dev:
    extends: .build
    variables:
        PROFILE: "dev"
    only:
        - dev

build-qa:
    extends: .build
    variables:
        PROFILE: "qa"
    only:
        - qa

build-prod:
    extends: .build
    variables:
        PROFILE: "prod"
    only:
        - master

build-others:
    extends: .build
    variables:
        PROFILE: "localdocker"
    except:
        - dev
        - qa
        - master
