stages:
    - dockerbuild

variables:
    V_NUM: "v0.0.1"
    CONTAINER_URL: "code.ornl.gov:4567/rse/datastreams/ssm/backend/ssm-bats-rest-api"

dockerbuild-fuseki:
    stage: dockerbuild
    script:
        - sudo systemctl stop docker
        - sudo rm -rf /var/lib/docker
        - sudo systemctl start docker
        - sudo docker rmi -f $CONTAINER_URL/fuseki/$CI_COMMIT_REF_NAME:$V_NUM
        - cd dockerfiles
        - docker build -f Dockerfile.fuseki -t $CONTAINER_URL/fuseki/$CI_COMMIT_REF_NAME:$V_NUM .
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CONTAINER_URL/fuseki/$CI_COMMIT_REF_NAME:$V_NUM
    tags:
        - rse-nds-builder

dockerbuild-ssm-bats-rest-api:
    stage: dockerbuild
    script:
        - sudo systemctl stop docker
        - sudo rm -rf /var/lib/docker
        - sudo systemctl start docker
        - sudo docker rmi -f $CONTAINER_URL/ssm-bats-rest-api/$CI_COMMIT_REF_NAME:$V_NUM
        - docker build -f dockerfiles/Dockerfile.ssm_bats_rest_api -t $CONTAINER_URL/ssm-bats-rest-api/$CI_COMMIT_REF_NAME:$V_NUM .
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CONTAINER_URL/ssm-bats-rest-api/$CI_COMMIT_REF_NAME:$V_NUM
    tags:
        - rse-nds-builder
