stages:
    - build-and-test

variables:
    V_NUM: "v0.0.1"
    CONTAINER_URL: "code.ornl.gov:4567/rse/datastreams/ssm/backend/ssm-bats-rest-api"

include:
    remote: "https://code.ornl.gov/rse-deployment/rse-sharables/-/raw/master/.gitlab-ci-before_script.yml"

build-ssm-bats-rest-api:
    stage: build-and-test
    script:
        - func_rse_docker_cleanup
        - sudo docker rmi -f $CONTAINER_URL/ssm-bats-rest-api/$CI_COMMIT_REF_NAME:$V_NUM
        - docker build -f dockerfiles/Dockerfile.ssm_bats_rest_api -t $CONTAINER_URL/ssm-bats-rest-api/$CI_COMMIT_REF_NAME:$V_NUM .
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CONTAINER_URL/ssm-bats-rest-api/$CI_COMMIT_REF_NAME:$V_NUM
    tags:
        - rse-nds-builder

test-ssm-bats-rest-api:
    stage: build-and-test
    script:
        - func_rse_docker_cleanup
        - docker build -f dockerfiles/Dockerfile.ssm_bats_rest_api.testing -t ssm-bats-test .
        - docker run -v /var/run/docker.sock:/var/run/docker.sock ssm-bats-test
        - func_rse_docker_cleanup
    tags:
        - rse-nds-builder

