version: '3.7'
services:
  fuseki:
    image: code.ornl.gov:4567/rse/datastreams/nuclear-datastreams/backend/bats-microservice/fuseki
    network_mode: "host"
    ports:
      - "3030:3030"
    volumes:
      - fuseki-TDB:/data/TDB:Z