version: '3'
services:
  fuseki:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.fuseki
    network_mode: "host"
    ports:
      - "3030:3030"
    volumes:
      - fuseki-TDB:/data/TDB:Z
  bats-microservice:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.bats_microservice
    network_mode: "host"
    ports:
      - "8080:8080"
volumes:
  fuseki-TDB: {}
