version: '3'
services:
  fuseki:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.fuseki
    networks:
      nds:
        aliases:
          - rse-nds-dev1.ornl.gov 
    ports:
      - "3030:3030"
    volumes:
      - /opt/fuseki-TDB:/data/TDB
  bats-microservice:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.ssm_bats_rest_api
    depends_on: 
       - fuseki
    networks:
      nds:
        aliases:
          - rse-nds-dev1.ornl.gov 
    ports:
      - "8080:8080"

networks:
  nds:
    driver: bridge
