version: '3'
services:
  fuseki:
    build:
      context: ./src/main/docker
      dockerfile: Dockerfile.fuseki
    ports:
      - "3030:3030"
    volumes:
      - /opt/fuseki-TDB:/data/TDB

  ssm-bats-rest-api:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.ssm_bats_rest_api
    depends_on: 
       - fuseki
    ports:
      - "8080:8080"
