version: '3'
services:
  fuseki:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.fuseki
    network_mode: "host"
    ports:
      - "3030:3030"
  bats-microservice:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.bats_microservice
    depends_on: 
       - fuseki
    network_mode: "host"
    ports:
      - "8080:8080"

