version: '3'
services:
  ssm-fuseki:
    # image: code.ornl.gov:4567/rse/datastreams/ssm/backend/ssm-bats-rest-api/fuseki:latest
    build:
      context: ./src/main/docker
      dockerfile: Dockerfile.fuseki
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - ./db-triple-store:/data/TDB

  ssm-document-store:
    build:
      context: ./src/main/docker
      dockerfile: Dockerfile.mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - ssm-document-store
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@ssm-document-store:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  ssm-bats-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - ssm-fuseki
      - ssm-document-store
    ports:
      - "8080:8080"
