version: '3'
services:
  ssm-fuseki:
    # image: code.ornl.gov:4567/rse/datastreams/ssm/backend/ssm-bats-rest-api/fuseki:latest
    build:
      context: ./src/main/docker
      dockerfile: Dockerfile.fuseki
    ports:
      - "3030:3030"
    volumes:
      - /opt/fuseki-TDB:/data/TDB

  ssm-document-store:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ssm-bats-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ssm-fuseki
      - ssm-document-store
    ports:
      - "8080:8080"
