version: '3'
services:
  postgres:
    container_name: ssm-postgres
    image: postgres
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  ssm-keycloak:
    image: keycloak-keycloak
    container_name: ssm-keycloak
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "8081:8080"
    environment:
      FEDERATE_LDAP: "true"
      GOOGLE_CLIENT_ID: XXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com
      GOOGLE_IDP: "true"
      GOOGLE_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/
      KC_DB_USERNAME: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      LDAP_URL: ldaps://LDAP_URL
      USERSDN: "dc=example,dc=com"
    depends_on:
      - postgres

  ssm-fuseki:
    network_mode: "host"
    build:
      context: ./src/main/docker
      dockerfile: Dockerfile.fuseki
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - ./db-triple-store:/data/TDB

  ssm-document-store:
    image: mongo:4
    restart: unless-stopped
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db-mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - ssm-document-store
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

  ssm-bats-rest-api:
    build:
      args:
        PROFILE: keycloak
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      PROFILE: keycloak
    depends_on:
      - ssm-fuseki
      - ssm-document-store
    command: "java -jar /app.jar --spring.data.mongodb.username=$MONGO_USERNAME --spring.data.mongodb.password=$MONGO_PASSWORD --server.port=8084"

