version: '3.7'
services:
  fuseki:
    image: code.ornl.gov:4567/rse/datastreams/nuclear-datastreams/backend/bats-microservice/fuseki
    ports:
      - "3030:3030"
    volumes:
      - /opt/fuseki-TDB:/data/TDB:Z
  bats-microservice:
    image: code.ornl.gov:4567/rse/datastreams/nuclear-datastreams/backend/bats-microservice/bats-microservice
    depends_on: 
       - fuseki
    ports:
      - "8080:8080"
