version: '3'
services:
  ssm-fuseki:
    # image: code.ornl.gov:4567/rse/datastreams/ssm/backend/ssm-bats-rest-api/fuseki:latest
    build:
      context: ./src/main/docker
      dockerfile: Dockerfile.fuseki
    ports:
      - "3030:3030"
    volumes:
      - /opt/fuseki-TDB:/data/TDB

  ssm-bats-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
       - ssm-fuseki
    ports:
      - "8080:8080"
