version: '3.7'
services:
  fuseki:
    image: code.ornl.gov:4567/rse/datastreams/ssm/backend/ssm-bats-rest-api/fuseki
    ports:
      - "3030:3030"
    volumes:
      - /opt/fuseki-TDB:/data/TDB:Z
  ssm-bats-rest-api:
    image: code.ornl.gov:4567/rse/datastreams/ssm/backend/ssm-bats-rest-api/ssm-bats-rest-api
    depends_on: 
       - fuseki
    ports:
      - "8080:8080"
