# Apply this profile IN ADDITION TO 'Docker' profile for the dev server

####################################################################
# Logging Config
logging.level.root=WARN
# print out the active profiles on startup
logging.level.ssm.catalog.SSMBatsRestApiApplication=INFO
####################################################################

####################################################################
# Hostname Configs
app.host=http://ssm-dev.ornl.gov
####################################################################
