FROM maven:3.6-jdk-11
ARG APP_DIR="/home/app"
WORKDIR ${APP_DIR}
COPY pom.xml ${APP_DIR}/pom.xml
RUN mvn -f ${APP_DIR}/pom.xml verify clean --fail-never
COPY src ${APP_DIR}/src
CMD ["mvn", "docker:build", "verify"]
